### ISSUE TITLE
Doesn't work on Android?

### ISSUE THREAD

**Issue by ROBYER1** [alibros/blazepose-unity#1]
Tried running on android, I get this error:

`2021/08/12 08:41:53.018 30665 30735 Error Unity DllNotFoundException: Unable to load DLL 'libtensorflowlite_c': The specified module could not be found.
`

**Comment by alibros** [comment]
he @ROBYER1 what device / OS version are you using?

**Comment by ROBYER1** [comment]
Xperia XZ3, Android 10

**Comment by ROBYER1** [comment]
Gonna close this as we found a different plugin
